Fix: Improve path handling
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -8,11 +8,11 @@ description: "Returns the current version of a Python Project"
 # Supports both pyproject.toml and setup.py project descriptions
 
 inputs:
+  # Mandatory
   PATH_PREFIX:
     description: "Directory location containing project code"
     type: string
     required: false
-    default: ""
 
 outputs:
   PYTHON_PROJECT_VERSION:
@@ -26,11 +26,30 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - name: "Setup action/environment"
+      shell: bash
+      run: |
+        # Setup action/environment
+        # Handle path_prefix input consistently and when absent
+        path_prefix="${{ inputs.PATH_PREFIX }}"
+        if [ -z "$path_prefix" ]; then
+          # Set current directory as path prefix
+          path_prefix="."
+        else
+          # Strip any trailing slash in provided path
+          path_prefix="${path_prefix%/}"
+        fi
+        # Verify is a valid directory path
+        if [ ! -d "$path_prefix" ]; then
+          echo "Error: invalid path/prefix to project directory ❌"; exit 1
+        fi
+        echo "path_prefix=$path_prefix" >> "$GITHUB_ENV"
+
     # yamllint disable-line rule:line-length
     - uses: lfreleng-actions/path-check-action@7f728b8ac404d3309cfa576f0ffc54217ade2faa # v0.1.1
       id: setup-py
       with:
-        path: "${{ inputs.path_prefix }}setup-py"
+        path: "${{ env.path_prefix }}/setup-py"
 
     - name: "Use project version from setup.py"
       id: setup-py-version
@@ -41,13 +60,13 @@ runs:
         flags: "-oP -m1"
         # https://regex101.com/r/QKYHId/1
         regex: '(?<=version=")([^"]*)'
-        filename: "${{ inputs.path_prefix }}setup.py"
+        filename: "${{ env.path_prefix }}/setup.py"
 
     # yamllint disable-line rule:line-length
     - uses: lfreleng-actions/path-check-action@7f728b8ac404d3309cfa576f0ffc54217ade2faa # v0.1.1
       id: pyproject-toml
       with:
-        path: "${{ inputs.path_prefix }}pyproject.toml"
+        path: "${{ env.path_prefix }}/pyproject.toml"
 
     - name: "Use project version from pyproject.toml"
       id: pyproject-toml-version
@@ -58,7 +77,7 @@ runs:
         flags: "-oP -m1"
         # https://regex101.com/r/MWmRge/1
         regex: '(?<=^version = ")([^"]*)'
-        filename: "${{ inputs.path_prefix }}pyproject.toml"
+        filename: "${{ env.path_prefix }}/pyproject.toml"
 
     - name: "Error: Python project metadata NOT found"
       if: steps.pyproject-toml.outputs.type == 'invalid' &&
